/**
/**
 * Engine — reads CONFIG, loads components, renders & animates.
 * DO NOT edit this file for customization. Edit config.js only.
 */

// ── Theme ────────────────────────────────────────────────────────
let currentMode = (CONFIG.defaultMode || "dark");

function applyTheme(mode) {
  currentMode = mode;
  const root = document.documentElement;
  const c = CONFIG.colors;

  root.style.setProperty("--primary", c.primary || "#8b5cf6");
  root.style.setProperty("--accent", c.accent || "#15a1ed");

  const theme = c[mode] || c.dark || {};
  root.style.setProperty("--bg", theme.background || "#1a1a2e");
  root.style.setProperty("--text", theme.text || "#ffffff");

  // Update toggle icon
  const btn = document.getElementById("theme-toggle");
  if (btn) btn.textContent = mode === "dark" ? "☀️" : "🌙";
}

function createThemeToggle() {
  const btn = document.createElement("button");
  btn.id = "theme-toggle";
  btn.type = "button";
  btn.title = "Toggle dark/light mode";
  btn.textContent = currentMode === "dark" ? "☀️" : "🌙";
  btn.addEventListener("click", () => {
    applyTheme(currentMode === "dark" ? "light" : "dark");
  });
  document.body.appendChild(btn);
}

// ── Music ────────────────────────────────────────────────────────
function createMusicToggle(audio) {
  if (!audio || !CONFIG.music) return;

  const btn = document.createElement("button");
  btn.id = "music-toggle";
  btn.type = "button";

  const updateButton = () => {
    const isPlaying = !audio.paused;
    btn.textContent = isPlaying ? "🔊" : "🔇";
    btn.title = isPlaying ? "Turn off music" : "Turn on music";
    btn.setAttribute("aria-label", btn.title);
    btn.setAttribute("aria-pressed", String(isPlaying));
  };

  btn.addEventListener("click", async () => {
    if (audio.paused) {
      try {
        await audio.play();
      } catch (error) {
        console.warn("Unable to play background music.", error);
      }
    } else {
      audio.pause();
    }
    updateButton();
  });

  audio.addEventListener("play", updateButton);
  audio.addEventListener("pause", updateButton);
  updateButton();
  document.body.appendChild(btn);
}

function unlockMusicAfterWin(audio) {
  if (!audio || !CONFIG.music) return;
  createMusicToggle(audio);
  audio.play().catch(() => {});
}

// ── Reading Pause ───────────────────────────────────────────────
const READING_SECTION_TYPES = new Set(["chatbox", "ideas", "quote", "profile"]);

function createReadingToggle(timeline) {
  const btn = document.createElement("button");
  btn.id = "reading-toggle";
  btn.type = "button";
  btn.setAttribute("aria-live", "polite");
  btn.setAttribute("aria-hidden", "true");

  const updateButton = () => {
    const isPaused = timeline.paused();
    btn.textContent = isPaused ? "▶ Continue" : "⏸ Pause";
    btn.title = isPaused ? "Continue" : "Pause";
    btn.setAttribute("aria-label", btn.title);
    btn.setAttribute("aria-pressed", String(isPaused));
  };

  btn.addEventListener("click", () => {
    if (timeline.paused()) {
      timeline.resume();
    } else {
      timeline.pause();
    }
    updateButton();
  });

  document.body.appendChild(btn);
  updateButton();

  return {
    setVisible(isVisible) {
      btn.classList.toggle("is-visible", isVisible);
      btn.setAttribute("aria-hidden", String(!isVisible));
      if (isVisible) updateButton();
    },
  };
}

// ── Opening Number Game ─────────────────────────────────────────
function startNumberGame(options = {}, onWin = () => {}) {
  if (options.enabled === false) return Promise.resolve();

  const secret = String(options.secret || "220426");
  const configuredAttempts = Number(options.maxAttempts);
  const maxAttempts = Number.isInteger(configuredAttempts) && configuredAttempts > 0
    ? configuredAttempts
    : 10;
  const configuredTeaseSeconds = Number(options.giftButtonTeaseSeconds);
  const giftButtonTeaseSeconds = Number.isFinite(configuredTeaseSeconds)
    && configuredTeaseSeconds >= 0
    ? configuredTeaseSeconds
    : 6;

  if (!/^\d+$/.test(secret)) {
    console.warn("Number game skipped: the secret must contain digits only.");
    return Promise.resolve();
  }

  return new Promise((resolve) => {
    const game = document.createElement("section");
    game.className = "number-game";
    game.setAttribute("aria-labelledby", "number-game-title");
    game.innerHTML = `
      <div class="number-game-card">
        <p class="number-game-kicker">Mini game</p>
        <h1 id="number-game-title">Đoán dãy số bí mật</h1>
        <p class="number-game-description">
          Nhập một dãy gồm <strong>${secret.length} chữ số</strong>.
          Mỗi chữ số đúng vị trí được tính là một điểm.
        </p>

        <form class="number-game-form" novalidate>
          <label class="visually-hidden" for="number-game-input">
            Dãy số bạn dự đoán
          </label>
          <input
            id="number-game-input"
            class="number-game-input"
            type="text"
            inputmode="numeric"
            autocomplete="off"
            maxlength="${secret.length}"
            placeholder="${"•".repeat(secret.length)}"
            aria-describedby="number-game-status"
          />
          <button class="number-game-submit" type="submit">Đoán</button>
        </form>

        <div class="number-game-meta">
          <span class="number-game-attempts">Còn ${maxAttempts} lượt</span>
          <span>${secret.length} vị trí cần tìm</span>
        </div>

        <p class="number-game-status" id="number-game-status" aria-live="polite">
          Hãy thử con số đầu tiên của bạn.
        </p>

        <button class="number-game-continue" type="button" hidden>
          Tiếp tục xem lời chúc
        </button>
        <ol class="number-game-history" aria-label="Lịch sử dự đoán"></ol>
      </div>
    `;

    const card = game.querySelector(".number-game-card");
    const form = game.querySelector(".number-game-form");
    const input = game.querySelector(".number-game-input");
    const submit = game.querySelector(".number-game-submit");
    const attemptsLabel = game.querySelector(".number-game-attempts");
    const status = game.querySelector(".number-game-status");
    const history = game.querySelector(".number-game-history");
    const continueButton = game.querySelector(".number-game-continue");
    let attemptsUsed = 0;
    let isFinished = false;
    let winConfettiAnimation = null;
    let giftButtonMoveTween = null;
    let giftButtonTeaseTimer = null;
    let giftButtonBaseRect = null;
    let isGiftButtonTeasing = false;
    let hasGiftButtonTeased = false;

    const setStatus = (message, tone = "default") => {
      status.textContent = message;
      status.dataset.tone = tone;
    };

    const countCorrectPositions = (guess) => {
      return [...guess].reduce((total, digit, index) => {
        return total + (digit === secret[index] ? 1 : 0);
      }, 0);
    };

    const addHistoryEntry = (guess, correctPositions) => {
      const item = document.createElement("li");
      const attempt = document.createElement("span");
      const number = document.createElement("code");
      const result = document.createElement("strong");

      attempt.textContent = `#${attemptsUsed}`;
      number.textContent = guess;
      result.textContent = `${correctPositions}/${secret.length} đúng`;
      item.append(attempt, number, result);
      history.prepend(item);
    };

    const playWinConfetti = () => {
      const layer = document.createElement("div");
      const colors = [
        CONFIG.colors.primary || "#8b5cf6",
        CONFIG.colors.accent || "#60a5fa",
        "#fbbf24",
        "#34d399",
        "#fb923c",
        "#f1f5f9",
      ];

      layer.className = "number-game-win-confetti";
      layer.setAttribute("aria-hidden", "true");

      for (let i = 0; i < 90; i++) {
        const piece = document.createElement("i");
        const width = 6 + Math.random() * 6;

        piece.className = "number-game-win-confetti-piece";
        piece.style.left = `${Math.random() * 100}%`;
        piece.style.width = `${width}px`;
        piece.style.height = `${width * (i % 3 === 0 ? 1 : 1.7)}px`;
        piece.style.backgroundColor = colors[i % colors.length];
        piece.dataset.startY = -30 - Math.random() * 160;
        piece.dataset.drift = (Math.random() - 0.5) * 180;
        piece.dataset.startRotation = (Math.random() - 0.5) * 180;
        piece.dataset.endRotation = 540 + Math.random() * 900;
        piece.dataset.duration = 2.2 + Math.random() * 1.2;
        layer.appendChild(piece);
      }

      game.prepend(layer);
      const pieces = layer.querySelectorAll(".number-game-win-confetti-piece");

      winConfettiAnimation = gsap.timeline({
        onComplete: () => {
          layer.remove();
          winConfettiAnimation = null;
        },
      });

      winConfettiAnimation.fromTo(pieces,
        {
          x: 0,
          y: (_, piece) => Number(piece.dataset.startY),
          rotation: (_, piece) => Number(piece.dataset.startRotation),
          opacity: 1,
        },
        {
          x: (_, piece) => Number(piece.dataset.drift),
          y: () => window.innerHeight + 80,
          rotation: (_, piece) => Number(piece.dataset.endRotation),
          opacity: 1,
          duration: (_, piece) => Number(piece.dataset.duration),
          stagger: { amount: 0.8, from: "random" },
          ease: "power1.inOut",
        }
      );
    };

    const moveGiftButton = (pointerX, pointerY) => {
      if (!isGiftButtonTeasing || !giftButtonBaseRect) return;

      const cardRect = card.getBoundingClientRect();
      const padding = 14;
      const safeLeft = Math.max(cardRect.left + padding, padding);
      const safeRight = Math.min(cardRect.right - padding, window.innerWidth - padding);
      const safeTop = Math.max(cardRect.top + padding, padding);
      const safeBottom = Math.min(cardRect.bottom - padding, window.innerHeight - padding);
      const minX = safeLeft - giftButtonBaseRect.left;
      const maxX = safeRight - giftButtonBaseRect.right;
      const minY = safeTop - giftButtonBaseRect.top;
      const maxY = safeBottom - giftButtonBaseRect.bottom;
      let nextX = 0;
      let nextY = 0;

      for (let attempt = 0; attempt < 8; attempt++) {
        const candidateX = gsap.utils.random(minX, maxX);
        const candidateY = gsap.utils.random(minY, maxY);
        const candidateCenterX = giftButtonBaseRect.left
          + giftButtonBaseRect.width / 2 + candidateX;
        const candidateCenterY = giftButtonBaseRect.top
          + giftButtonBaseRect.height / 2 + candidateY;

        nextX = candidateX;
        nextY = candidateY;
        if (Math.hypot(candidateCenterX - pointerX, candidateCenterY - pointerY) > 120) {
          break;
        }
      }

      if (giftButtonMoveTween) giftButtonMoveTween.kill();
      giftButtonMoveTween = gsap.to(continueButton, {
        x: nextX,
        y: nextY,
        rotation: gsap.utils.random(-4, 4),
        duration: 0.16,
        ease: "power3.out",
        overwrite: true,
      });
    };

    const finishGiftButtonTease = () => {
      if (!isGiftButtonTeasing) return;

      isGiftButtonTeasing = false;
      hasGiftButtonTeased = true;
      giftButtonTeaseTimer = null;
      continueButton.classList.remove("is-teasing");
      setStatus("Giỡn một xíu thôi 😄 Giờ ông có thể mở quà rồi!", "success");

      if (giftButtonMoveTween) giftButtonMoveTween.kill();
      giftButtonMoveTween = null;
      gsap.set(continueButton, { clearProps: "transform" });
    };

    const startGiftButtonTease = (event) => {
      const supportsHover = window.matchMedia("(hover: hover) and (pointer: fine)").matches;
      if (
        !supportsHover
        || giftButtonTeaseSeconds <= 0
        || continueButton.dataset.result !== "win"
        || hasGiftButtonTeased
      ) {
        return;
      }

      if (!isGiftButtonTeasing) {
        isGiftButtonTeasing = true;
        giftButtonBaseRect = continueButton.getBoundingClientRect();
        continueButton.classList.add("is-teasing");
        setStatus("","hint");
        giftButtonTeaseTimer = window.setTimeout(
          finishGiftButtonTease,
          giftButtonTeaseSeconds * 1000
        );
      }

      moveGiftButton(event.clientX, event.clientY);
    };

    const closeGame = () => {
      if (isFinished) return;
      isFinished = true;
      if (winConfettiAnimation) winConfettiAnimation.kill();
      if (giftButtonMoveTween) giftButtonMoveTween.kill();
      if (giftButtonTeaseTimer) window.clearTimeout(giftButtonTeaseTimer);
      gsap.to(game, {
        opacity: 0,
        y: -20,
        duration: 0.5,
        ease: "power2.inOut",
        onComplete: () => {
          game.remove();
          resolve();
        },
      });
    };

    input.addEventListener("input", () => {
      input.value = input.value.replace(/\D/g, "").slice(0, secret.length);
    });

    form.addEventListener("submit", (event) => {
      event.preventDefault();
      const guess = input.value;

      if (guess.length !== secret.length) {
        setStatus(`Vui lòng nhập đủ ${secret.length} chữ số.`, "error");
        input.focus();
        return;
      }

      attemptsUsed += 1;
      const correctPositions = countCorrectPositions(guess);
      const attemptsLeft = maxAttempts - attemptsUsed;

      addHistoryEntry(guess, correctPositions);
      attemptsLabel.textContent = `Còn ${attemptsLeft} lượt`;

      if (correctPositions === secret.length) {
        input.disabled = true;
        submit.disabled = true;
        setStatus(
          `Chính xác! Bạn đã tìm ra dãy số sau ${attemptsUsed} lượt. Món quà đang chờ bạn!`,
          "success"
        );
        continueButton.textContent = "Mở món quà 🎁";
        continueButton.dataset.result = "win";
        continueButton.hidden = false;
        playWinConfetti();
        gsap.fromTo(continueButton,
          { opacity: 0, y: 14, scale: 0.96 },
          {
            opacity: 1, y: 0, scale: 1, duration: 0.5,
            ease: "back.out(1.7)",
          }
        );
        window.setTimeout(() => continueButton.focus({ preventScroll: true }), 500);
        return;
      }

      if (attemptsUsed >= maxAttempts) {
        form.hidden = true;
        attemptsLabel.textContent = "Đã hết lượt";
        continueButton.textContent = "↻ Chơi lại từ đầu";
        continueButton.dataset.result = "retry";
        continueButton.hidden = false;
        setStatus(
          `Bạn chưa tìm ra dãy số sau ${maxAttempts} lượt. Hãy tải lại trang để thử lại nhé!`,
          "error"
        );
        continueButton.focus();
        return;
      }

      setStatus(
        `Bạn có ${correctPositions}/${secret.length} vị trí đúng. Thử lại nhé!`,
        correctPositions > 0 ? "hint" : "default"
      );
      input.value = "";
      input.focus();
    });

    continueButton.addEventListener("pointerenter", startGiftButtonTease);

    continueButton.addEventListener("click", (event) => {
      if (isFinished) return;

      if (
        continueButton.dataset.result === "win"
        && isGiftButtonTeasing
        && event.detail > 0
      ) {
        event.preventDefault();
        moveGiftButton(event.clientX, event.clientY);
        return;
      }

      if (continueButton.dataset.result === "retry") {
        window.location.reload();
        return;
      }

      if (continueButton.dataset.result === "win") {
        continueButton.disabled = true;
        onWin();
      }

      closeGame();
    });
    document.body.appendChild(game);

    gsap.from(card, {
      opacity: 0,
      y: 24,
      scale: 0.96,
      duration: 0.6,
      ease: "power2.out",
    });

    window.setTimeout(() => input.focus({ preventScroll: true }), 450);
  });
}

// ── Script Loader ────────────────────────────────────────────────
function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement("script");
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error("Component not found: " + src));
    document.head.appendChild(s);
  });
}

// ── Main ─────────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", async () => {
  applyTheme(currentMode);
  createThemeToggle();

  // Set music source
  const audio = document.querySelector(".song");
  if (audio && CONFIG.music) {
    audio.volume = Math.min(1, Math.max(0, Number(CONFIG.musicVolume ?? 1)));
    audio.querySelector("source").src = CONFIG.music;
    audio.load();
  }

  // Determine unique component types
  const types = [...new Set(CONFIG.sections.map((s) => s.type))];

  // Dynamically load component scripts
  for (const type of types) {
    try {
      await loadScript(`./script/components/${type}.js`);
    } catch (e) {
      console.warn(e.message);
    }
  }

  // Render all sections
  const container = document.querySelector(".container");
  const rendered = [];

  CONFIG.sections.forEach((section) => {
    const comp = window.Components && window.Components[section.type];
    if (!comp) {
      console.warn(`Component "${section.type}" not found, skipping.`);
      return;
    }
    const el = comp.render(container, section, CONFIG);
    rendered.push({ el, comp, section });
  });

  await startNumberGame(CONFIG.game, () => unlockMusicAfterWin(audio));
  buildTimeline(rendered);
});

// ── Timeline Builder ─────────────────────────────────────────────
function buildTimeline(rendered) {
  const tl = gsap.timeline();
  const readingToggle = createReadingToggle(tl);

  tl.to(".container", { duration: 0.6, visibility: "visible" });

  // Track deferred exits for overlay components
  let deferredExits = [];

  rendered.forEach(({ el, comp, section }, i) => {
    const isOverlay = comp.overlay === true;

    // Flush deferred exits before non-overlay sections
    if (!isOverlay && deferredExits.length > 0) {
      deferredExits.forEach((fn) => fn());
      deferredExits = [];
    }

    if (!isOverlay) {
      const canPauseForReading = READING_SECTION_TYPES.has(section.type);
      tl.call(() => readingToggle.setVisible(canPauseForReading));
    }

    // Animate
    comp.animate(tl, el, CONFIG);

    // Handle exit lifecycle
    if (comp.exit) {
      const next = rendered[i + 1];
      const nextIsOverlay = next && next.comp.overlay === true;

      if (nextIsOverlay) {
        deferredExits.push(() => comp.exit(tl, el));
      } else if (!isOverlay) {
        comp.exit(tl, el);
      }
    }
  });

  // Flush remaining
  deferredExits.forEach((fn) => fn());

  // Setup replay
  const replayBtn = document.getElementById("replay");
  if (replayBtn) {
    replayBtn.addEventListener("click", () => tl.restart());
  }
}
